use_frameworks!

platform :ios, '16.2'

target 'MFAuthAccess_Example' do
  pod 'Alamofire', '~> 5.7.1'
  pod 'MFAuthAccess', :path => '../'
  
  target 'MFAuthAccess_Tests' do
    inherit! :search_paths

    
  end
end
