# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestingMFAuthAccess' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestingMFAuthAccess
    pod 'MFAuthAccess'

  target 'TestingMFAuthAccessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestingMFAuthAccessUITests' do
    # Pods for testing
  end

end
